[supervisord]
nodaemon=true

[program:backend]
directory=/app/backend
command=python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_error.log
environment=ENVIRONMENT="production"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true



