name: Build and Push Docker Image to ECR

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/github-ecr-role
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set image vars
      run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ vars.REPO_NAME }}:latest" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t $IMAGE_URI .

    - name: Push Docker image
      run: docker push $IMAGE_URI


